// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/bytecamp-galaxy/mini-tiktok/cmd/api/biz/jwt"
	"github.com/bytecamp-galaxy/mini-tiktok/cmd/api/biz/model/api"
	"github.com/bytecamp-galaxy/mini-tiktok/cmd/api/biz/pack"
	"github.com/bytecamp-galaxy/mini-tiktok/internal/convert"
	id "github.com/bytecamp-galaxy/mini-tiktok/internal/redis"
	"github.com/bytecamp-galaxy/mini-tiktok/internal/rpc"
	"github.com/bytecamp-galaxy/mini-tiktok/kitex_gen/feed"
	"github.com/bytecamp-galaxy/mini-tiktok/pkg/conf"
	"github.com/bytecamp-galaxy/mini-tiktok/pkg/errno"
	"github.com/bytecamp-galaxy/mini-tiktok/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/pkg/kerrors"
	"github.com/marmotedu/errors"
)

// GetFeed .
// @router /douyin/feed/ [GET]
// @description 视频流接口：不限制登录状态，返回按投稿时间倒序的视频列表，视频数由服务端控制，单次最多 30 个
// @produce application/json
// @param q query api.FeedRequest true "feed request"
// @success 200 {object} api.FeedResponse
func GetFeed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FeedRequest

	err = c.BindAndValidate(&req)
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrBindAndValidation, err.Error()))
		return
	}

	// get the latest time.
	// if the latest time hasn't been passed as param, it's 0 by default.
	latestTime := req.GetLatestTime()
	uid := id.InvalidUserId

	// if token is passed
	if req.GetToken() != api.FeedRequest_Token_DEFAULT {
		// fetch user view id from token
		userId, ok := c.Get(jwt.IdentityKey)
		if !ok {
			pack.Error(c, errors.WithCode(errno.ErrParseToken, ""))
			return
		}
		uid = userId.(int64)
	}

	// set up connection with feed server
	v := conf.Init()
	cli, err := rpc.InitFeedClient(v.GetString("api-server.name"))
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrClientRPCInit, err.Error()))
		return
	}

	// call rpc service
	reqRpc := &feed.FeedRequest{
		UserViewId: uid,
		LatestTime: &latestTime,
	}

	respRpc, err := (*cli).GetFeed(ctx, reqRpc)
	if err != nil {
		if bizErr, ok := kerrors.FromBizStatusError(err); ok {
			pack.Error(c, errors.WithCode(int(bizErr.BizStatusCode()), bizErr.BizMessage()))
			return
		} else {
			pack.Error(c, errors.WithCode(errno.ErrRPCLink, err.Error()))
			return
		}
	}

	// convert model.Videos to feed.Videos
	respVideos := make([]*api.Video, len(respRpc.VideoList))
	for i, video := range respRpc.VideoList {
		respVideos[i] = convert.VideoConverterAPI(video)
	}

	// response to client
	resp := &api.FeedResponse{
		StatusCode: errno.ErrSuccess,
		StatusMsg:  utils.String(pack.SuccessStatusMessage),
		VideoList:  respVideos,
		NextTime:   respRpc.NextTime,
	}

	c.JSON(consts.StatusOK, resp)
}
