// Code generated by hertz generator.

package api

import (
	"bytes"
	"context"
	"github.com/bytecamp-galaxy/mini-tiktok/cmd/api/biz/jwt"
	"github.com/bytecamp-galaxy/mini-tiktok/cmd/api/biz/model/api"
	"github.com/bytecamp-galaxy/mini-tiktok/cmd/api/biz/pack"
	"github.com/bytecamp-galaxy/mini-tiktok/internal/convert"
	"github.com/bytecamp-galaxy/mini-tiktok/internal/rpc"
	"github.com/bytecamp-galaxy/mini-tiktok/kitex_gen/publish"
	"github.com/bytecamp-galaxy/mini-tiktok/pkg/conf"
	"github.com/bytecamp-galaxy/mini-tiktok/pkg/errno"
	"github.com/bytecamp-galaxy/mini-tiktok/pkg/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/pkg/kerrors"
	"github.com/marmotedu/errors"
	"io"
)

// PublishAction .
// @router /douyin/publish/action/ [POST]
// @description 投稿接口：登录用户选择视频上传
// @produce application/json
// @param f formData api.PublishActionRequest true "publish action request"
// @success 200 {object} api.PublishActionResponse
func PublishAction(ctx context.Context, c *app.RequestContext) {
	// NOTE: DO NOT USE `BindAndValidate`
	fileHeader, err := c.Request.FormFile("data")
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrBindAndValidation, err.Error()))
		return
	}

	// get .mp4 data
	file, err := fileHeader.Open()
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrOpenFormFile, err.Error()))
		return
	}
	defer file.Close()

	buf := bytes.NewBuffer(nil)
	if _, err := io.Copy(buf, file); err != nil {
		pack.Error(c, errors.WithCode(errno.ErrEncodingFailed, err.Error()))
		return
	}

	// fetch user id from token
	userId, ok := c.Get(jwt.IdentityKey)
	if !ok {
		pack.Error(c, errors.WithCode(errno.ErrParseToken, ""))
		return
	}

	// set up connection with publish server
	v := conf.Init()
	cli, err := rpc.InitPublishClient(v.GetString("api-server.name"))
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrClientRPCInit, err.Error()))
		return
	}

	// call rpc service
	reqRpc := &publish.PublishRequest{
		UserId: userId.(int64),
		Data:   buf.Bytes(),
		Title:  c.PostForm("title"),
	}

	_, err = (*cli).PublishVideo(ctx, reqRpc)
	if err != nil {
		if bizErr, ok := kerrors.FromBizStatusError(err); ok {
			pack.Error(c, errors.WithCode(int(bizErr.BizStatusCode()), bizErr.BizMessage()))
			return
		} else {
			pack.Error(c, errors.WithCode(errno.ErrRPCLink, err.Error()))
			return
		}
	}

	resp := &api.PublishActionResponse{
		StatusCode: errno.ErrSuccess,
		StatusMsg:  utils.String(pack.SuccessStatusMessage),
	}

	c.JSON(consts.StatusOK, resp)
}

// PublishList .
// @router /douyin/publish/list/ [GET]
// @description 发布列表：用户的视频发布列表，直接列出用户所有投稿过的视频
// @produce application/json
// @param q query api.PublishListRequest true "publish list request"
// @success 200 {object} api.PublishListResponse
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.PublishListRequest

	err = c.BindAndValidate(&req)
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrBindAndValidation, err.Error()))
		return
	}

	// fetch user view id from token
	userViewId, ok := c.Get(jwt.IdentityKey)
	if !ok {
		pack.Error(c, errors.WithCode(errno.ErrParseToken, ""))
		return
	}

	// set up connection with publish server
	v := conf.Init()
	cli, err := rpc.InitPublishClient(v.GetString("api-server.name"))
	if err != nil {
		pack.Error(c, errors.WithCode(errno.ErrClientRPCInit, err.Error()))
		return
	}

	// call rpc service
	reqRpc := &publish.PublishListRequest{
		UserId:     req.GetUserId(),
		UserViewId: userViewId.(int64),
	}

	respRpc, err := (*cli).PublishList(ctx, reqRpc)
	if err != nil {
		if bizErr, ok := kerrors.FromBizStatusError(err); ok {
			pack.Error(c, errors.WithCode(int(bizErr.BizStatusCode()), bizErr.BizMessage()))
			return
		} else {
			pack.Error(c, errors.WithCode(errno.ErrRPCLink, err.Error()))
			return
		}
	}

	// convert model.Videos to feed.Videos
	respVideos := make([]*api.Video, len(respRpc.VideoList))
	for i, video := range respRpc.VideoList {
		respVideos[i] = convert.VideoConverterAPI(video)
	}
	resp := &api.PublishListResponse{
		StatusCode: errno.ErrSuccess,
		StatusMsg:  utils.String(pack.SuccessStatusMessage),
		VideoList:  respVideos,
	}

	c.JSON(consts.StatusOK, resp)
}
